version: "3.9"
services:
  postgres:
    image: "postgres:15.2-alpine"
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - database-data:/var/lib/postgresql/blog/

volumes:
  database-data:
    driver: local
